config/routes.rb
Rails.application.routes.draw do
  # See how all your routes lay out with "rake routes".
  resources :links, :only => [:create, :new]
  devise_for :users
  #note: This is the option that we can authenticate the routes based on routes
	# authenticated do
	#    root to: "links#new", as: :authenticated_root
	# end
  # You can have the root of your site routed with "root"
  root 'links#new'
  #named resource
  get '/stats', to: 'links#index', as: 'stats'
  get ':short_url' => 'links#go'
end

app/models/click.rb
class Click < ActiveRecord::Base
	belongs_to :user
	belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates_presence_of :given_url
  has_many :clicks
  has_many :users, :through => :clicks
  validates :given_url, format: URI::regexp(%w[http https])

  def shorten(url)
    chars = ['0'..'9', 'A'..'Z', 'a'..'z'].map { |range| range.to_a }.flatten
    self.shortened_url = 5.times.map { chars.sample }.join
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :clicks
    has_many :links, :through => :clicks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/links_controller.rb
require 'socket'
require 'date'

class LinksController < ApplicationController
  #If i remove this line even the authentication will work once i have been removed the commented line from routes
  before_filter :authenticate_user!, only: [:new,:create]
  before_action :get_location
  respond_to :html, :js

  attr_reader :ip_address
  attr_reader :country

  def index
    @links = Link.includes(:clicks)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @link = Link.new
  end

  def go
    link = Link.find_by(shortened_url: params["short_url"])
    click = Click.where(link: link.id).last
    if link.created_at < link.created_at + 30.days
      if click && click.user_id == current_user.id
        click.count += 1
        click.save
      elsif click && click.user_id != current_user.id
        click.count = 0
        Click.create(link_id: link.id, user_id: current_user.id, count: "#{click.count += 1}", ip_address: ip_address, country: country)
      end
      redirect_to link.given_url
    else
      link.destroy
      render :file => 'public/404.html', :status => :not_found, :layout => false 
    end
  end

  def create
    @link = Link.new(link_params)
    unless link_params["given_url"].empty?
      url = @link.shorten(link_params["given_url"])
      @link.given_url = link_params["given_url"]
      @link.shortened_url = url
    end
    respond_to do |format|
      if @link.save
        Click.create(link_id: @link.id, user_id: current_user.id, count: 0, ip_address: ip_address, country: country)
        format.js 
        format.json
        format.html { render :new }
      else
        format.js 
        format.html { render :new, notice: 'Enter valid URL'}
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_location
      @ip_address = current_user.current_sign_in_ip
      @country = Geocoder.search(ip_address).first.country
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:given_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SHORTENED URL</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container">
   <div class="navbar navbar-static-top">

     <a class="navbar-brand" href="/"> <div class="glyphicon glyphicon-link"> Shortened URL</div></a>
     <div class="nav-collapse">
        <ul class="nav navbar-nav">
        </ul>
         <ul class="nav navbar-nav pull-right">
           <li class="active"><%= link_to "Stats",stats_path %></li>
           <% if user_signed_in? %>
                 <li><%=link_to "#{current_user.email}"%></li>
                 <li class="active"><%= link_to "Logout",destroy_user_session_path%></li>
             <%else%>
                 <li><%= link_to "Login", new_user_session_path %></li>
                  <li class="active"><%= link_to "SignUp", new_user_registration_path%></li>
             <%end%>
         </ul>
     </div><!--/.nav-collapse -->
   </div>
  <div class="row">
    <div class="col-lg-2">
    </div>
    <div class="col-lg-9">
      <div id="search_result">

      </div>
      <div id="main_block">
         <%= yield %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for @link, remote: true do |f| %>

  <div class="field">
    <%= f.label :enter_url %><br>
    <%= f.text_field :given_url %>
  </div>

  <div class="actions">
    <%= f.submit 'Shorten Me',:class => "btn btn-primary" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<% if @link.errors.any? %>
	<div id="error_explanation">
	  <% @link.errors.full_messages.each do |message| %>
	    <%= message %>
	  <% end %>
	</div>
<% else %>
	<p>
	  <strong>Shortened url:</strong>
	  <%= link_to "#{request.base_url}/#{link.shortened_url}", link.shortened_url, target: '_blank' %>
	</p>
<% end %>

app/views/links/create.js.erb
$('#link').html("<%= j (render @link) %>");
$('#link').show();

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Analytics</h1>
<div class="row">
  <table  class="table">
    <thead>
      <tr>
        <th>Shortened url</th>
        <th>Clicks</th>
        <th>Ip Address</th>
        <th>Country</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @links.each do |link| %>
        <tr>

          <td><%= link_to "#{request.base_url}/#{link.shortened_url}", link.shortened_url, target: '_blank' %></td>
          <td><%= link.clicks.map(&:count).inject(:+)%></td>
          <td><%= link.clicks.order("count DESC").first.ip_address %></td>
          <td><%= link.clicks.order("count DESC").first.country %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<div class="row">
  <div class="col-md-7 col-md-offset-1" id="link" style="display:none;"><%= render @link%></div>
</div>

app/views/links/new.js.erb
$('#link-form').html("<%= j (render 'form') %>");
$('#link-form').slideDown(350);